### ISSUE TITLE
Actividad1_Infografia

### ISSUE THREAD

**Issue by 22620188Oliverio** [SistemasTecTlaxiaco/actividad-1-infografia-22620188Oliverio#1]
[CicloDeVidaDelDesarrolloDesoftware.pdf](https://github.com/user-attachments/files/16755023/CicloDeVidaDelDesarrolloDesoftware.pdf)

**Comment by Kim-Mendoza3** [comment]
Calificacion 18

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
